I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/dungeon.rpy", line 82, in script
    jump dungeon_no_arron_betray
ScriptError: could not find label 'dungeon_no_arron_betray'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/dungeon.rpy", line 82, in script
    jump dungeon_no_arron_betray
  File "/Users/christianfitzpatrick/Desktop/Games/renpy-8.0.3-sdk/renpy/ast.py", line 1974, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/christianfitzpatrick/Desktop/Games/renpy-8.0.3-sdk/renpy/script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'dungeon_no_arron_betray'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.0.3.22090809
soj2023 1.0
Sun Apr  2 22:27:45 2023
